[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"

[profile.release]
evm_version = "berlin"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
